// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxSummary.Infrastructure.Data;

#nullable disable

namespace TaxSummary.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaxSummaryDbContext))]
    [Migration("20260909065746_AddPayrollRulesEnforcementAndDeputyTier")]
    partial class AddPayrollRulesEnforcementAndDeputyTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("TaxSummary.Domain.Entities.AdministrativeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("DelayAndAbsenceHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HourlyLeaveHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("MissionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("OvertimeHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("PaidLeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SickLeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("DelayAndAbsenceHours")
                        .HasDatabaseName("IX_AdministrativeStatuses_DelayAndAbsenceHours");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_AdministrativeStatuses_EmployeeId");

                    b.ToTable("AdministrativeStatuses", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedColumns")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Employees_CreatedAt");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_Employees_FirstName");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_Employees_LastName");

                    b.HasIndex("NationalId")
                        .HasDatabaseName("IX_Employees_NationalId");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_PersonnelNumber");

                    b.HasIndex("ServiceUnit")
                        .HasDatabaseName("IX_Employees_ServiceUnit");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Employees_LastName_FirstName");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.MenuSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdminOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Admin,Manager,Employee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("MenuKey")
                        .IsUnique();

                    b.HasIndex("ParentKey");

                    b.ToTable("MenuSettings", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FinalizedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FinalizedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("FiscalYear", "FiscalMonth");

                    b.ToTable("PayrollCycles", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollDepartmentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BaseBonusCap")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseOvertimeCap")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseWelfareCap")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeputyApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeputyApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GroupHeadBonusCap")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OtherStaffBonusCap")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PayrollCycleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("SeniorExpertBonusCap")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("DeputyApprovedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("PayrollCycleId", "DepartmentName")
                        .IsUnique();

                    b.ToTable("PayrollDepartmentEntries", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollEmployeeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedBonusAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjustedOvertimeRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjustedWelfareRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseBonusAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseOvertimeAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseWelfareAmount")
                        .HasColumnType("REAL");

                    b.Property<long?>("CalculatedOvertimeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CalculatedWelfareAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("InitialOvertimeRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitialWelfareRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLaborPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxBonusLimit")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxOvertimeLimit")
                        .HasColumnType("REAL");

                    b.Property<string>("OfficerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentEntryId", "PersonnelNumber");

                    b.ToTable("PayrollEmployeeItems", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("PayrollRuns", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PerformanceCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompanyIdentification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("CompanyIdentification_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CompanyIdentification_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CompanyIdentification_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("DetectionOfTaxEvasion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DetectionOfTaxEvasion_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("DetectionOfTaxEvasion_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("DetectionOfTaxIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DetectionOfTaxIssues_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("DetectionOfTaxIssues_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Jobs_Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jobs_Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jobs_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Other_Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Other_Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Other_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReferredOrExecuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ReferredOrExecuted_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ReferredOrExecuted_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("ValueAddedRecognition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ValueAddedRecognition_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ValueAddedRecognition_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ValueAddedRecognition_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_PerformanceCapabilities_EmployeeId");

                    b.HasIndex("SystemRole")
                        .HasDatabaseName("IX_PerformanceCapabilities_SystemRole");

                    b.ToTable("PerformanceCapabilities", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.RefundableReceiptAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefundableAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("RevenueLedgerRow")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxRefundCaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxRefundReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalReceiptAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxRefundReceiptId");

                    b.HasIndex("TaxRefundCaseId", "TaxRefundReceiptId");

                    b.ToTable("RefundableReceiptAllocations", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxRefundCaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxRefundCaseId", "ActionDate");

                    b.ToTable("TaxRefundApprovalActions", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdministrationHeadName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseTrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EconomicCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupHeadName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeniorAuditorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShebaNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxUnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxpayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseTrackingNumber")
                        .IsUnique();

                    b.HasIndex("EconomicCode");

                    b.HasIndex("Status");

                    b.HasIndex("TaxYear");

                    b.HasIndex("TaxpayerName", "TaxYear");

                    b.ToTable("TaxRefundCases", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedLetterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedReceiptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxRefundCaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadDateJalali")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedByUserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedLetterId");

                    b.HasIndex("RelatedReceiptId");

                    b.HasIndex("TaxRefundCaseId");

                    b.HasIndex("TaxRefundCaseId", "DocumentType");

                    b.ToTable("TaxRefundDocuments", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DebtAmount")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtYear")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LetterDateJalali")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("LetterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LetterType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaxRefundCaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxRefundCaseId", "LetterType");

                    b.ToTable("TaxRefundLetters", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountRials")
                        .HasPrecision(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueDateJalali")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentDateJalali")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RevenueLedgerRow")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaxRefundCaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptNumber");

                    b.HasIndex("TaxRefundCaseId", "RowIndex");

                    b.ToTable("TaxRefundReceipts", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.AdministrativeStatus", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithOne("AdministrativeStatus")
                        .HasForeignKey("TaxSummary.Domain.Entities.AdministrativeStatus", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollCycle", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxSummary.Domain.Entities.User", "FinalizedBy")
                        .WithMany()
                        .HasForeignKey("FinalizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("FinalizedBy");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollDepartmentEntry", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxSummary.Domain.Entities.User", "DeputyApprovedBy")
                        .WithMany()
                        .HasForeignKey("DeputyApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxSummary.Domain.Entities.PayrollCycle", "PayrollCycle")
                        .WithMany("DepartmentEntries")
                        .HasForeignKey("PayrollCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxSummary.Domain.Entities.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");

                    b.Navigation("DeputyApprovedBy");

                    b.Navigation("PayrollCycle");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollEmployeeItem", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.PayrollDepartmentEntry", "DepartmentEntry")
                        .WithMany("Items")
                        .HasForeignKey("DepartmentEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentEntry");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollRun", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PerformanceCapability", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithMany("PerformanceCapabilities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.RefundableReceiptAllocation", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.TaxRefundCase", "TaxRefundCase")
                        .WithMany("Allocations")
                        .HasForeignKey("TaxRefundCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxSummary.Domain.Entities.TaxRefundReceipt", "TaxRefundReceipt")
                        .WithMany()
                        .HasForeignKey("TaxRefundReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRefundCase");

                    b.Navigation("TaxRefundReceipt");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundApprovalAction", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.TaxRefundCase", "TaxRefundCase")
                        .WithMany("Approvals")
                        .HasForeignKey("TaxRefundCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRefundCase");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundCase", b =>
                {
                    b.OwnsOne("TaxSummary.Domain.Entities.JustificationReportInfo", "JustificationReport", b1 =>
                        {
                            b1.Property<Guid>("TaxRefundCaseId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AdministrationHeadApprovalText")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_AdministrationHeadApprovalText");

                            b1.Property<string>("AuditExaminationFindings")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_AuditExaminationFindings");

                            b1.Property<string>("AuditorConclusion")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_AuditorConclusion");

                            b1.Property<string>("AuditorSignatureDate")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_AuditorSignatureDate");

                            b1.Property<Guid?>("AuditorUserId")
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_AuditorUserId");

                            b1.Property<string>("AuditorUserName")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_AuditorUserName");

                            b1.Property<DateTime?>("FinalizedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_FinalizedAt");

                            b1.Property<string>("GroupHeadOpinionText")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_GroupHeadOpinionText");

                            b1.Property<string>("InquiriesAndDebtClearanceSummary")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_InquiriesAndDebtClearanceSummary");

                            b1.Property<bool>("IsFinalized")
                                .HasColumnType("INTEGER")
                                .HasColumnName("JustificationReport_IsFinalized");

                            b1.Property<string>("LegalGroundsAndReasoning")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_LegalGroundsAndReasoning");

                            b1.Property<string>("ReceiptsVerificationNotes")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_ReceiptsVerificationNotes");

                            b1.Property<decimal>("RecommendedRefundAmount")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_RecommendedRefundAmount");

                            b1.Property<string>("ReportDateJalali")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_ReportDateJalali");

                            b1.Property<string>("ReportNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("JustificationReport_ReportNumber");

                            b1.HasKey("TaxRefundCaseId");

                            b1.ToTable("TaxRefundCases");

                            b1.WithOwner()
                                .HasForeignKey("TaxRefundCaseId");
                        });

                    b.OwnsOne("TaxSummary.Domain.Entities.RefundBreakdown", "Breakdown", b1 =>
                        {
                            b1.Property<Guid>("TaxRefundCaseId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("DelayDamages")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Breakdown_DelayDamages");

                            b1.Property<decimal>("OtherRefund")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Breakdown_OtherRefund");

                            b1.Property<decimal>("PenaltiesRefund")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Breakdown_PenaltiesRefund");

                            b1.Property<decimal>("PrincipalTaxRefund")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Breakdown_PrincipalTaxRefund");

                            b1.Property<decimal>("StampDutyRefund")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Breakdown_StampDutyRefund");

                            b1.HasKey("TaxRefundCaseId");

                            b1.ToTable("TaxRefundCases");

                            b1.WithOwner()
                                .HasForeignKey("TaxRefundCaseId");
                        });

                    b.OwnsOne("TaxSummary.Domain.Entities.TaxAssessmentInfo", "AssessmentInfo", b1 =>
                        {
                            b1.Property<Guid>("TaxRefundCaseId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AssessedIncome")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_AssessedIncome");

                            b1.Property<decimal>("AssessedTax")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_AssessedTax");

                            b1.Property<decimal>("Exemptions")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_Exemptions");

                            b1.Property<string>("FinalNoticeDateJalali")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_FinalNoticeDateJalali");

                            b1.Property<string>("FinalNoticeNumber")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_FinalNoticeNumber");

                            b1.Property<int>("FinalityStage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(1)
                                .HasColumnName("Assessment_FinalityStage");

                            b1.Property<int>("FinalizationMethod")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Assessment_FinalizationMethod");

                            b1.Property<bool>("HasReturnFiled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Assessment_HasReturnFiled");

                            b1.Property<decimal>("NonWaivablePenalties")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_NonWaivablePenalties");

                            b1.Property<string>("ReturnDateJalali")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_ReturnDateJalali");

                            b1.Property<string>("ReturnNumber")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_ReturnNumber");

                            b1.Property<decimal>("TimelyPaymentBonus")
                                .HasPrecision(18)
                                .HasColumnType("TEXT")
                                .HasColumnName("Assessment_TimelyPaymentBonus");

                            b1.HasKey("TaxRefundCaseId");

                            b1.ToTable("TaxRefundCases");

                            b1.WithOwner()
                                .HasForeignKey("TaxRefundCaseId");
                        });

                    b.Navigation("AssessmentInfo")
                        .IsRequired();

                    b.Navigation("Breakdown")
                        .IsRequired();

                    b.Navigation("JustificationReport")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundDocument", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.TaxRefundCase", "TaxRefundCase")
                        .WithMany("Documents")
                        .HasForeignKey("TaxRefundCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRefundCase");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundLetter", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.TaxRefundCase", "TaxRefundCase")
                        .WithMany("Letters")
                        .HasForeignKey("TaxRefundCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRefundCase");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundReceipt", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.TaxRefundCase", "TaxRefundCase")
                        .WithMany("Receipts")
                        .HasForeignKey("TaxRefundCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRefundCase");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.User", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("TaxSummary.Domain.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AdministrativeStatus");

                    b.Navigation("PerformanceCapabilities");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollCycle", b =>
                {
                    b.Navigation("DepartmentEntries");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollDepartmentEntry", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.TaxRefundCase", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Approvals");

                    b.Navigation("Documents");

                    b.Navigation("Letters");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
