// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxSummary.Infrastructure.Data;

#nullable disable

namespace TaxSummary.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaxSummaryDbContext))]
    [Migration("20260831172052_AddCollaborativePayrollCycles")]
    partial class AddCollaborativePayrollCycles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("TaxSummary.Domain.Entities.AdministrativeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("DelayAndAbsenceHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HourlyLeaveHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("MissionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("OvertimeHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("PaidLeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SickLeaveDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("DelayAndAbsenceHours")
                        .HasDatabaseName("IX_AdministrativeStatuses_DelayAndAbsenceHours");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_AdministrativeStatuses_EmployeeId");

                    b.ToTable("AdministrativeStatuses", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Employees_CreatedAt");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_Employees_FirstName");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_Employees_LastName");

                    b.HasIndex("NationalId")
                        .HasDatabaseName("IX_Employees_NationalId");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_PersonnelNumber");

                    b.HasIndex("ServiceUnit")
                        .HasDatabaseName("IX_Employees_ServiceUnit");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Employees_LastName_FirstName");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FinalizedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FinalizedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("FiscalYear", "FiscalMonth");

                    b.ToTable("PayrollCycles", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollDepartmentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("BaseBonusCap")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseOvertimeCap")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseWelfareCap")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PayrollCycleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("PayrollCycleId", "DepartmentName")
                        .IsUnique();

                    b.ToTable("PayrollDepartmentEntries", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollEmployeeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedOvertimeRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("AdjustedWelfareRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseBonusAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseOvertimeAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseWelfareAmount")
                        .HasColumnType("REAL");

                    b.Property<long?>("CalculatedOvertimeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CalculatedWelfareAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("InitialOvertimeRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitialWelfareRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfficerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentEntryId", "PersonnelNumber");

                    b.ToTable("PayrollEmployeeItems", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("PayrollRuns", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PerformanceCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompanyIdentification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("CompanyIdentification_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CompanyIdentification_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CompanyIdentification_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("DetectionOfTaxEvasion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DetectionOfTaxEvasion_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("DetectionOfTaxEvasion_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("DetectionOfTaxIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("DetectionOfTaxIssues_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("DetectionOfTaxIssues_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Jobs_Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jobs_Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jobs_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Other_Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Other_Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Other_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReferredOrExecuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ReferredOrExecuted_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ReferredOrExecuted_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("ValueAddedRecognition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ValueAddedRecognition_Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ValueAddedRecognition_Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ValueAddedRecognition_UndetectedQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_PerformanceCapabilities_EmployeeId");

                    b.HasIndex("SystemRole")
                        .HasDatabaseName("IX_PerformanceCapabilities_SystemRole");

                    b.ToTable("PerformanceCapabilities", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.AdministrativeStatus", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithOne("AdministrativeStatus")
                        .HasForeignKey("TaxSummary.Domain.Entities.AdministrativeStatus", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollCycle", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxSummary.Domain.Entities.User", "FinalizedBy")
                        .WithMany()
                        .HasForeignKey("FinalizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("FinalizedBy");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollDepartmentEntry", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxSummary.Domain.Entities.PayrollCycle", "PayrollCycle")
                        .WithMany("DepartmentEntries")
                        .HasForeignKey("PayrollCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxSummary.Domain.Entities.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");

                    b.Navigation("PayrollCycle");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollEmployeeItem", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.PayrollDepartmentEntry", "DepartmentEntry")
                        .WithMany("Items")
                        .HasForeignKey("DepartmentEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentEntry");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollRun", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PerformanceCapability", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithMany("PerformanceCapabilities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.User", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("TaxSummary.Domain.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AdministrativeStatus");

                    b.Navigation("PerformanceCapabilities");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollCycle", b =>
                {
                    b.Navigation("DepartmentEntries");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PayrollDepartmentEntry", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
