// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxSummary.Infrastructure.Data;

#nullable disable

namespace TaxSummary.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaxSummaryDbContext))]
    [Migration("20260916083000_AddCycleCodeToPayrollCycles")]
    partial class AddCycleCodeToPayrollCycles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");
#pragma warning restore 612, 618
        }
    }
}
