// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxSummary.Infrastructure.Data;

#nullable disable

namespace TaxSummary.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaxSummaryDbContext))]
    partial class TaxSummaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxSummary.Domain.Entities.AdministrativeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("DelayAndAbsenceHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HourlyLeaveHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IncentiveHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MissionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("DelayAndAbsenceHours")
                        .HasDatabaseName("IX_AdministrativeStatuses_DelayAndAbsenceHours");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("IX_AdministrativeStatuses_EmployeeId");

                    b.ToTable("AdministrativeStatuses", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("PreviousExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("ServiceUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Employees_CreatedAt");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_Employees_LastName");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_PersonnelNumber");

                    b.HasIndex("ServiceUnit")
                        .HasDatabaseName("IX_Employees_ServiceUnit");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PerformanceCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CompanyIdentification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("DetectionOfTaxEvasion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("DetectionOfTaxIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ReferredOrExecuted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<bool>("ValueAddedRecognition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_PerformanceCapabilities_EmployeeId");

                    b.HasIndex("SystemRole")
                        .HasDatabaseName("IX_PerformanceCapabilities_SystemRole");

                    b.ToTable("PerformanceCapabilities", (string)null);
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.AdministrativeStatus", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithOne("AdministrativeStatus")
                        .HasForeignKey("TaxSummary.Domain.Entities.AdministrativeStatus", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.PerformanceCapability", b =>
                {
                    b.HasOne("TaxSummary.Domain.Entities.Employee", "Employee")
                        .WithMany("PerformanceCapabilities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TaxSummary.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AdministrativeStatus");

                    b.Navigation("PerformanceCapabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
